/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-05-22 15:03:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.fantastic5.skkmprogram.*;

public final class MainFrame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("    <title>Products - IF532 JSP</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/dataTables.bootstrap.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\tbody { font-size: 140%; }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#header{\r\n");
      out.write("\t\t\tbackground: #50A5E6;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.headerFont {\r\n");
      out.write("\t\t\tcolor: #fff\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.gambarHeader {\r\n");
      out.write("\t\t\theight: 16px;\r\n");
      out.write("\t\t\twidht: 16px;\r\n");
      out.write("\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\tmargin-top: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#navbar-header-font {\r\n");
      out.write("\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\tfont-family: Helvetica, Georgia, Verdana;\r\n");
      out.write("\t\t\twidth: 450px;\r\n");
      out.write("\t\t\tmargin-bottom: -10px;\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.circular {\r\n");
      out.write("\t\t\twidth: 32px;\r\n");
      out.write("\t\t\theight: 32px;\r\n");
      out.write("\t\t\tborder-radius: 150px;\r\n");
      out.write("\t\t\tmargin-top: -5px;\r\n");
      out.write("\t\t\tmargin-right: 5px;\r\n");
      out.write("\t\t\t-webkit-border-radius: 150px;\r\n");
      out.write("\t\t\t-moz-border-radius: 150px;\r\n");
      out.write("\t\t\tbackground: url(http://link-to-your/image.jpg) no-repeat;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.list-group.panel > .list-group-item {\r\n");
      out.write("\t\t  border-bottom-right-radius: 4px;\r\n");
      out.write("\t\t  border-bottom-left-radius: 4px\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.list-group-submenu {\r\n");
      out.write("\t\t  margin-left:20px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#left-side {\r\n");
      out.write("\t\t\twidth: 25%;\r\n");
      out.write("\t\t\theight: auto;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#right-side {\r\n");
      out.write("\t\t\twidth: 75%;\r\n");
      out.write("\t\t\theight: auto;\r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"container-fluid\" id=\"header\">\r\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t  <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t  <a class=\"navbar-brand\" href=\"#\" style=\"color: white; float:left;\">\r\n");
      out.write("\t\t\t  \t<img src=\"./images/umnwhite.png\" style=\"width: 32px; height: auto; margin-top: -10px;\">\r\n");
      out.write("\t\t\t  \t\r\n");
      out.write("\t\t\t  </a>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  <div class=\"navbar-brand\"  id=\"navbar-header-font\">Credit Units of Student Activities</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\" >\r\n");
      out.write("\t\t\t  <ul class=\"nav navbar-nav navbar-right\" >\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a ><img src=\"./images/pp_domarco.jpg\" class=\"circular\"> <span style=\"color: white;\">Welcome Domarco </span><span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a><img src=\"./icons/bell.png\"  class=\"gambarHeader\"> </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a><img src=\"./icons/gear.png\"  class=\"gambarHeader\">  </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t  </ul>\r\n");
      out.write("\t\t\t</div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t</div><!-- /.container-fluid -->\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#example').dataTable();\r\n");
      out.write("\t\t} );\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h1> It Works!</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container-fluid\" id=\"left-side\">\r\n");
      out.write("\t\t<div id=\"MainMenu\">\r\n");
      out.write("\t\t  \t<div class=\"list-group panel\">\r\n");
      out.write("\t\t\t    <a href=\"#demo3\" class=\"list-group-item list-group-item-success\" data-toggle=\"collapse\" data-parent=\"#MainMenu\">Item 3</a>\r\n");
      out.write("\t\t\t    <div class=\"collapse\" id=\"demo3\">\r\n");
      out.write("\t\t\t      \t<a href=\"#SubMenu1\" class=\"list-group-item\" data-toggle=\"collapse\" data-parent=\"#SubMenu1\">Subitem 1 <i class=\"fa fa-caret-down\"></i></a>\r\n");
      out.write("\t\t\t      \t<div class=\"collapse list-group-submenu\" id=\"SubMenu1\">\r\n");
      out.write("\t\t\t\t        <a href=\"#\" class=\"list-group-item\" data-parent=\"#SubMenu1\">Subitem 1 a</a>\r\n");
      out.write("\t\t\t\t        <a href=\"#\" class=\"list-group-item\" data-parent=\"#SubMenu1\">Subitem 2 b</a>\r\n");
      out.write("\t\t\t\t        <a href=\"#SubSubMenu1\" class=\"list-group-item\" data-toggle=\"collapse\" data-parent=\"#SubSubMenu1\">Subitem 3 c <i class=\"fa fa-caret-down\"></i></a>\r\n");
      out.write("\t\t\t\t        <div class=\"collapse list-group-submenu list-group-submenu-1\" id=\"SubSubMenu1\">\r\n");
      out.write("\t\t\t\t          \t<a href=\"#\" class=\"list-group-item\" data-parent=\"#SubSubMenu1\">Sub sub item 1</a>\r\n");
      out.write("\t\t\t\t          \t<a href=\"#\" class=\"list-group-item\" data-parent=\"#SubSubMenu1\">Sub sub item 2</a>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t        \t<a href=\"#\" class=\"list-group-item\" data-parent=\"#SubMenu1\">Subitem 4 d</a>\r\n");
      out.write("\t\t\t      \t</div>\r\n");
      out.write("\t\t\t      \t<a href=\"javascript:;\" class=\"list-group-item\">Subitem 2</a>\r\n");
      out.write("\t\t\t      \t<a href=\"javascript:;\" class=\"list-group-item\">Subitem 3</a>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <a href=\"#demo4\" class=\"list-group-item list-group-item-success\" data-toggle=\"collapse\" data-parent=\"#MainMenu\">Item 4</a>\r\n");
      out.write("\t\t\t    <div class=\"collapse\" id=\"demo4\">\r\n");
      out.write("\t\t\t      \t<a href=\"\" class=\"list-group-item\">Subitem 1</a>\r\n");
      out.write("\t\t\t      \t<a href=\"\" class=\"list-group-item\">Subitem 2</a>\r\n");
      out.write("\t\t\t      \t<a href=\"\" class=\"list-group-item\">Subitem 3</a>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> <!-- /container fluid vertical accordion -->\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"container-fluid\" id=\"right-side\">\r\n");
      out.write("    \t<button type=\"button\" class=\"btn openpanel\">Open panel 3</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn closepanel\">Close panel 3</button>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t                <a class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#panel1\">Panel 1</a>\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"panel1\" class=\"panel-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t                Contents panel 1\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t                <a class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#panel2\">Panel 2</a>\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"panel2\" class=\"panel-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t                Contents panel 2\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t                <a class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#panel3\">Panel 3</a>\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"panel3\" class=\"panel-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t                Contents panel 3\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(\".openpanel\").on(\"click\", function() {\r\n");
      out.write("\t\t\t    $(\".collapse\").collapse('show');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\".closepanel\").on(\"click\", function() {\r\n");
      out.write("\t\t\t    $(\".panel-collapse\").collapse('hide');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* ensure any open panels are closed before showing selected */\r\n");
      out.write("\t\t\t$('#accordion').on('show.bs.collapse', function () {\r\n");
      out.write("\t\t\t    $('#accordion .in').collapse('hide');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("    </div> <!--  container fluid button accordion -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
